# fly.toml app configuration file generated for react-task-manager on 2024-04-27T12:16:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'react-task-manager'
primary_region = 'mad'

[env]
  PORT = '3000'
  ALLOWED_ORIGINS = 'https://react-task-manager.fly.dev'
  SESSION_SECURE = 'true'

[build]
[build.args]
  VITE_BASE_API_URL = 'https://react-task-manager.fly.dev/v1'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
